### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by newage404** [nodemasterpro/deploy-node-berachain#1]
After using the 
ansible-playbook bera_node.yml -e node_action="install"
It gives error ![Screenshot_20240415-075430.jpg](https://github.com/nodemasterpro/deploy-node-berachain/assets/125931712/e21e5202-ea3d-48bf-8492-024bfc61ff00)

**Comment by nasbuild** [comment]
Type this command: 
ansible-playbook berachain_node.yml -e node_action="install"
